# Generated by Django 5.0.3 on 2024-03-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodocurso',
            name='numero',
            field=models.IntegerField(verbose_name='Numero periodo'),
        ),
    ]
