# Generated by Django 5.2.1 on 2025-06-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_periodocurso_numero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoas',
            new_name='Pessoa',
        ),
        migrations.AlterField(
            model_name='cursos',
            name='carga_horaria_total',
            field=models.CharField(max_length=4, verbose_name='Carga horaria total'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao', verbose_name='Nome da instituição'),
        ),
    ]
